### ISSUE TITLE
No support for UUID or ULID User ID

### ISSUE THREAD

**Issue by nsouto** [saasscaleup/laravel-console-log#1]
Hello,

I'm just letting you know that the package assumes an INT user id when some applications could be using UUID or ULID.

If I have time I will try to PR an update that would support both.

The other thing is the migration has a set date instead of naming the file with the current date so that it's in chronological order, even though it shouldn't interfere with anything else, and this is just my opinion it would be better.

Great work on the package though, very useful and thank you for your time.

Regards,
Nuno

**Comment by saasscaleup** [comment]
Hey @nsouto And thanks for sharing your inputs. Feel free to PR and update use. If we will have time, We will do that too :)
